models:
  - name: yolov8n
    pretrained: yolov8n.pt
    imgsz: 320
    batch: 32
    epochs: 10
    device: "cpu"
  
  - name: yolov8s
    pretrained: yolov8s.pt
    imgsz: 320
    batch: 16
    epochs: 10
    device: "cpu"
  
  - name: yolov8m
    pretrained: yolov8m.pt
    imgsz: 320
    batch: 8
    epochs: 10
    device: "cpu"